#! /bin/zsh

bspc rule -r "*"
bspc rule -a Chromium desktop='2' follow=off
bspc rule -a Brave-browser desktop='2' follow=off border=off
bspc rule -a firefox desktop='2' follow=off
bspc rule -a qutebrowser desktop='2' follow=off

bspc rule -a Signal desktop='3' follow=off state=tiled
bspc rule -a ViberPC desktop='3' focus=off follow=off

bspc rule -a qBittorrent desktop='4' follow=on
bspc rule -a Thunar desktop='4' follow=on
bspc rule -a libreoffice-startcenter desktop='4' follow=on

bspc rule -a Lutris desktop='4' follow=on
bspc rule -a Zathura state=tiled


feh --bg-scale $HOME/.wp.jpg &
$HOME/.config/polybar/launch.sh &
pkill picom
picom &
if ! pgrep -u $UID -x dunst >/dev/null; then
	numlockx &
        xgamma -quiet -rgamma 0.90 -ggamma 0.90 -bgamma 0.90 &
	sxhkd &
	setxkbmap us,gr -option 'grp:caps_toggle' &
	$HOME/.toggle_touchpad.sh &
	brave &
	urxvt &
	urxvt &
	signal-desktop &
	xsetroot -cursor_name left_ptr &
fi
dunst &

bspc monitor eDP-1 -d 1 2 3 4 7 8 9 0
bspc monitor HDMI-2 -d 5 6

bspc config ignore_ewmh_focus true
#bspc config ignore_ewmh_fullscreen all

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color   \#3b3b3b
bspc config focused_border_color  \#d79921
bspc config presel_feedback_color \#282828
