#! /bin/zsh


bspc rule -r "*"
bspc rule -a Chromium desktop=Browser focus=off follow=off border=off
bspc rule -a Signal desktop=Messaging focus=off follow=off
bspc rule -a ViberPC desktop=Messaging focus=off follow=off
bspc rule -a Lutris desktop=Gaming follow=on
bspc rule -a Thunar desktop=Others follow=on
bspc rule -a qBittorrent desktop=Others follow=on
bspc rule -a libreoffice-startcenter desktop=Others follow=on

mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

if ! echo "$mainmonitor" | grep LVDS >/dev/null 2>&1; then
	xrandr --output "$mainmonitor" --auto --output LVDS1 --off
fi

feh --bg-scale $HOME/.wp.jpg &
if ! pgrep -u $UID -x polybar >/dev/null; then
	sxhkd &
	setxkbmap us,gr -option 'grp:caps_toggle' &
	$HOME/.toggle_touchpad.sh &
	picom &
	chromium &
	urxvt &
	urxvt &
	signal-desktop &
	i3-battery-popup -n &
	dunst &
	xsetroot -cursor_name left_ptr &
fi
$HOME/.config/polybar/launch.sh &

bspc monitor $mainmonitor -d Terminals Browser Messaging Others Gaming

bspc config border_width         4
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color   \#002b36
bspc config focused_border_color  \#d33682
bspc config presel_feedback_color \#002b36
